@startuml

autonumber

ProjectManager --> AutomaticAssignmentOrdersUI : automatically assign orders
AutomaticAssignmentOrdersUI --> AutomaticAssignController :
AutomaticAssignController --> AutomaticAssignOrderService
AutomaticAssignOrderService --> TcpSrvAgvManager
TcpSrvAgvManager -> TcpSrvAgvManager : automaticTaskAssignment()
TcpSrvAgvManager --> orderRepository : ordersToBePrepared()
TcpSrvAgvManager --> agvRepository : findAvailableAGVS()
TcpSrvAgvManager --> AGV : assignOrder(order)
TcpSrvAgvManager --> ForceOrderOnAGVUI
ForceOrderOnAGVUI --> ProjectManager : orders assign


@enduml