@startuml

autonumber

WarehouseEmployee --> ForceOrderOnAGVUI : chooses to force an order
ForceOrderOnAGVUI --> AssignOrderController :
AssignOrderController --> ListOrderToBePreparedService
ForceOrderOnAGVUI --> WarehouseEmployee : asks to choose an order
WarehouseEmployee --> ForceOrderOnAGVUI : Inserts the order he wants to force
ForceOrderOnAGVUI --> AssignOrderController :
AssignOrderController --> AssignOrderService :
AssignOrderService --> TcpSrvAgvManager : connects
TcpSrvAgvManager --> AGVRepository
TcpSrvAgvManager --> OrderRepository
TcpSrvAgvManager --> ForceOrderOnAGVUI :
ForceOrderOnAGVUI --> WarehouseEmployee : sucessful



@enduml