@startuml

class BaseBackoffice{
    -MainMenu menu
}

class ForceOrderOnAGVUI{
    ForceOrderOnAGVController forceOrderOnAGVController;
}

class AssignOrderController{
    -AuthorizationService authz;
    -SystemUser currentUser;
    -AssignOrderService assignOrderService
    -ListOrderToBePreparedService listOrderToBePreparedService
}

class ListOrderToBePreparedService{
}

class FindOrderByIdService{
}

class AssignOrderService{
}

interface AGVRepository{
}

interface OrderRepository{
}

class TcpSrvAgvManager{
}

BaseBackoffice -> ForceOrderOnAGVUI

ForceOrderOnAGVUI -> AssignOrderController

AssignOrderController -down-> ListOrderToBePreparedService
AssignOrderController -down-> FindOrderByIdService
AssignOrderController -down-> FindAGVReadyService
AssignOrderController -down-> FindAGVByIdService
AssignOrderController -down-> AssignOrderService

AssignOrderService -right-> TcpSrvAgvManager : Connects

ListOrderToBePreparedService -down-> OrderRepository
FindOrderByIdService -down-> OrderRepository
FindAGVReadyService -down-> AGVRepository
FindAGVByIdService -down-> AGVRepository

@enduml