@startuml
'https://plantuml.com/class-diagram

Surveys <<Entity root>>
package AgregadoQuestionnaire {
Questionnaire <<Entity root>>
Section <<Entity>>
Question <<Entity>>
}

Surveys "1" -right-> "1" Questionnaire
Questionnaire "1" --> "*" Section
Section "1" --> "*" Question

@enduml