@startuml
left to right direction
skinparam linetype ortho

class WareHousePlant<<entity root>> {
}

class Aisles<<entity>>{

}

class Rows<<entity>>{

}

class AVGDocks<<entity>>{

}

class Accessibility<<value object>>{

}

WareHousePlant "1" -> "*"  AVGDocks
WareHousePlant "1" -> "*" Aisles
Aisles "1" -> "1*" Rows
Aisles "1" -> "1" Accessibility

@enduml