@startuml

Entity WareHousePlant<<entity root>> {
 -long id **PRIMARY KEY**;
 -int length
 -int square
 -String unit
 -List<Aisle> listAisles
}

Entity Aisle<<entity>>{
    -long id **PRIMARY KEY**;
    -int idWareHouse **FOREIGN KEY**;
    -Accessibility accessibility;
    -List<Row> listRows;
}

Entity Row<<entity>>{
    -long id **PRIMARY KEY**;
    -int idAisles **FOREIGN KEY**;
    -int shelves;
}

Entity AGVDock<<entity>>{
    -long id **PRIMARY KEY**;
    -Accessibility accessibility;
}

class Accessibility<<value object>>{
    -String accessibility;

}

Entity AGV<<entity>>{
    -long id **PRIMARY KEY**;
    -String description;
    -String model;
    -double maxWeight;
    -double maxVolume;
    -boolean status;
    -int positionX;
    -int positionY;
    -int autonomyMin;
    -Task task;
    -AGVDock agvDock;
}

Entity Task<<entity>>{
    -long id **PRIMARY KEY**;
    -AGV agvResp;
    -String status;
    -List<Products> listProducts;
}

WareHousePlant "1" -> "*"  AGVDock
WareHousePlant "1" -> "*" AGV
WareHousePlant "1" -> "*" Aisle
Aisle "1" -> "1*" Row
Aisle "1" -> "1" Accessibility
AGV "1" -> "1" AGVDock
AGV "1" -> "1" Task
AGVDock "1" -> "1" Accessibility

@enduml