@startuml

Entity AGV<<entity>>{

}

class ConfigureAGVUI{
    ConfigureAGVController configureAGVController;
}

class ConfigureAGVController{
    -AGVRepository agvRepository;
    -AuthorizationService authz;
    -AGVBuilder agvBuilder;
    -configureAGV();
}

class AGVBuilder{
    -build()
    -buildOrThrow(){
}

class BaseBackoffice{
    -MainMenu menu
}

interface AGVRepository{

}

interface DomainFactory{

}

class JpaAGVRepository{

}

class JpaAutoTxRepository{

}

class InMemoryAGVRepository{

}

class InMemoryDomainRepository{

}

class JpaRepositoryFactory{
    -AGVRepository agv();
}

interface RepositoryFactory{

}

AGVBuilder -down-> AGV

BaseBackoffice -> ConfigureAGVUI

ConfigureAGVUI -> ConfigureAGVController

ConfigureAGVController ->  AGVBuilder

ConfigureAGVController -down-> RepositoryFactory
RepositoryFactory -right-> AGVRepository


AGVRepository -right-> DomainFactory : "extends"

JpaAGVRepository -right-> JpaRepositoryFactory
JpaRepositoryFactory -> AGVRepository

JpaAGVRepository  -> JpaAutoTxRepository : "extends"
JpaAGVRepository -down-> AGVRepository : "implements"

InMemoryAGVRepository -down-> InMemoryDomainRepository : "extends"
InMemoryAGVRepository -down-> AGVRepository : "implements"

@enduml