
@startuml

left to right direction
skinparam linetype ortho

class AGV<<entity root>>{

}

class AutonomyHours<<value object>>{

}

class Status<<value object>>{

}

class MaxWeight<<value object>>{

}

class MaxVolume<<value object>>{

}

class Position<<value object>>{

}

class Task<<entity>>{

}

AGV "1" -> "1" Position
Task "1" <-> "1" AGV
AGV "1" -> "1" MaxWeight
AGV "1" -> "1" MaxVolume
AGV "1" -> "1" AutonomyHours
AGV "1" -> "1" Status


@enduml